---
title: "CleanData"
output: html_document
---
## To do 2017/04/02
* Parallel computing of mice
* More impuatation methods (missForest)
* Time series 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(plyr)
library(dplyr)
library(mice) # for imputation
library(zoo) # for time series
```


```{r clean}
train.raw = read.csv("../data/train.csv")
test.raw = read.csv("../data/test.csv")
# combine train and test for imputation, without SalePrice
all.raw = rbind(subset(train.raw, select=-SalePrice), test.raw)

# get data type
data.type = sapply(all.raw,function(x) class(x))
data.type
table(data.type)

# basement variables
var.bsmt = colnames(all.raw[, 31:39])
var.bsmt
# garage variables
var.grg = colnames(all.raw[, 59:65])
var.grg

# summarize missing values and fill those NAs that are "none",
# except for basement and garage variables
var.na = colnames(all.raw)[apply(all.raw, 2, anyNA)]
sapply(all.raw[var.na], function(x) sum(is.na(x)))

var.none = c("Alley", "PoolQC", "Fence", "MiscFeature")
all.raw[, names(all.raw) %in% var.none] = "None"

# ===============fill bsmt and grg================#

# ================================================











#================= old code ================================
# only the following variables have NAs
na.var = c("LotFrontage", "MasVnrType", "MasVnrArea", "Electrical")
train.na = train.raw[na.var]
train.nna = train.raw[, !names(train.raw) %in% na.var]
summary(train.raw[na.var])

# extract factor variables, including non-numerical ordinal variables,
# OverallQual and OverallCond are numerical and ordinal 
is.fact = sapply(train.nna, is.factor)
# GarageYrBlt has NA and is discrete, force to be factor 
train.fact = train.nna[, is.fact] %>% 
  cbind(GarageYrBlt = train.raw$GarageYrBlt)
train.nonfact = train.nna[, !is.fact] %>% subset(select=-GarageYrBlt)
# replace NAs with "None"
train.fact = sapply(train.fact, as.character)
train.fact[is.na(train.fact)] = "None"
train.fact = sapply(as.data.frame(train.fact), as.factor)
# merge with train.nonfact
train = cbind(train.fact, train.nonfact) %>% cbind(train.na)




# ------------------------------------------------------------
# use cart in the "mice" package to impute NA
# https://www.kaggle.com/c/house-prices-advanced-regression-techniques/discussion/24586
# more methods to be tried
#-------------------------------------------------------------
tmp = mice(train, m=1, maxit=500, meth='cart', seed=0, printFlag=F)
train = complete(tmp, 1)

write.csv(train, "../data/trainCleaned.csv")
```
